 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/assets", type: :request do
  # Asset. As you add validations to Asset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Asset.create! valid_attributes
      get assets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      asset = Asset.create! valid_attributes
      get asset_url(asset)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_asset_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      asset = Asset.create! valid_attributes
      get edit_asset_url(asset)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Asset" do
        expect {
          post assets_url, params: { asset: valid_attributes }
        }.to change(Asset, :count).by(1)
      end

      it "redirects to the created asset" do
        post assets_url, params: { asset: valid_attributes }
        expect(response).to redirect_to(asset_url(Asset.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Asset" do
        expect {
          post assets_url, params: { asset: invalid_attributes }
        }.to change(Asset, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post assets_url, params: { asset: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested asset" do
        asset = Asset.create! valid_attributes
        patch asset_url(asset), params: { asset: new_attributes }
        asset.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the asset" do
        asset = Asset.create! valid_attributes
        patch asset_url(asset), params: { asset: new_attributes }
        asset.reload
        expect(response).to redirect_to(asset_url(asset))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        asset = Asset.create! valid_attributes
        patch asset_url(asset), params: { asset: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested asset" do
      asset = Asset.create! valid_attributes
      expect {
        delete asset_url(asset)
      }.to change(Asset, :count).by(-1)
    end

    it "redirects to the assets list" do
      asset = Asset.create! valid_attributes
      delete asset_url(asset)
      expect(response).to redirect_to(assets_url)
    end
  end
end
